services:
  - type: web
    name: student-management-backend
    runtime: python
    plan: free
    rootDirectory: student_management_system
    buildCommand: ./build.sh
    startCommand: daphne -b 0.0.0.0 -p $PORT student_management.asgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DJANGO_SETTINGS_MODULE
        value: student_management.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: '*'
